name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script_stop: true
          script: |
            cd ~/next-blog
            git pull --rebase
            export N_PREFIX=$HOME/.n
            export PATH=$N_PREFIX/bin:$PATH
            npm ci
            npm run build
            npm test --if-present
            pm2 restart all --silent
